### ISSUE TITLE
Use deprecated check as a result "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by jesuscicd** [danielfm/aws-limits-exporter#13]
![IMAGE 2020-11-19 14:50:38](https://user-images.githubusercontent.com/50547944/99668558-96d54980-2a76-11eb-8760-991223daca17.jpg)
You still using deprecated check as a result service was broke:

```
I1118 18:56:03.297280       1 main.go:26] AWS Limits Exporter v0.3.0 started.
I1118 18:56:03.297516       1 support.go:172] Refreshing Trusted Advisor check 'fW7HH0l7J9'...
I1118 18:56:04.156563       1 support.go:172] Refreshing Trusted Advisor check 'aW7HH0l7J9'...
I1118 18:56:04.195935       1 support.go:172] Refreshing Trusted Advisor check 'gW7HH0l7J9'...
I1118 18:56:04.224868       1 support.go:172] Refreshing Trusted Advisor check '6gtQddfEw6'...
I1118 18:56:04.272984       1 support.go:172] Refreshing Trusted Advisor check 'c5ftjdfkMr'...
E1118 18:56:04.302451       1 support.go:233] Cannot retrieve Trusted Advisor check results data: InvalidParameterValueException: Unknown ID: fH7LL0l7J9
 status code: 400, request id: 6a61d26e-732d-40fc-a055-76098a6779cb
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x92a213]
goroutine 21 [running]:
github.com/danielfm/aws-limits-exporter/core.(*SupportExporter).Describe(0xc00020aed0, 0xc0000a5200)
 /build/core/support.go:236 +0x5a3
github.com/prometheus/client_golang/prometheus.(*Registry).Register.func1(0xc14680, 0xc00020aed0, 0xc0000a5200)
 /go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:274 +0x3b
created by github.com/prometheus/client_golang/prometheus.(*Registry).Register
 /go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:273 +0x154
```

**Comment by danielfm** [comment]
Fixed in #12
